# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

num_runs: 1
experiment: "pmnist"
experiment_name: "pmnist_no_meta"
data_dir: "../data"
checkpoint: "./checkpoints/"

ntasks: 10
n_channels: 1

lr_out: 0.01
lr_inner: 0.1

out_epochs: 80
pri_epochs: 1
mini_tasks: 0
inner_loop: 1

head_units: 28
latent_dim: 64

batch_size: 256
pc_valid: 0.15
val_iter: 10

workers: 4
seed: 48