# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

experiment: "miniimagenet"
experiment_name: "miniimagenet"
data_dir: "../data"
checkpoint: "./checkpoints/"

# Experiment
num_runs: 3
ntasks: 20
n_channels: 3
workers: 4
seed: 48

#Train
epochs: 70
feats_epochs: 20 #20
meta_epochs: 10
epochs_inner_task: 1
batch_size: 128
pc_valid: 0.02
lr_meta: 0.001 #0.001 
lr_task: 0.01

#Model
head_units: 128
latent_dim: 256
resnet18: False
task_embedding: False

#Meta
use_meta: False #
mini_tasks: 30 #80
inner_loop: 30 #75

# #Modelo Completo:
use_share: True
use_private: True
use_mask: True
only_shared: False

# Memory
use_memory: False
prob_use_mem: 0.5
mem_size: 5

# Use last private model to get masks
use_last_pri: False

#Extra
get_masks: False
use_one_representation: False
save_model: False
