# Base on the code: https://github.com/facebookresearch/Adversarial-Continual-Learning

experiment: "miniimagenet"
experiment_name: "miniimagenet"
data_dir: "../data"
checkpoint: "./checkpoints/"

# Experiment
num_runs: 3
ntasks: 20
n_channels: 3
workers: 4
seed: 48
num_iter: 1

#Train
epochs: 70
feats_epochs: 40 #20
meta_epochs: 10
batch_size: 128
pc_valid: 0.02
lr_meta: 0.001 #0.001 
lr_task: 0.01

#Model
head_units: 128
latent_dim: 256
resnet18: True
use_relu: False
use_pca: True

#Meta
use_meta: True #
mini_tasks: 10 #80
inner_loop: 40 #75

# #Modelo Completo:
use_share: True
use_mask: True
only_shared: False

# Memory
use_memory: False
prob_use_mem: 0.5
mem_size: 5

# Use last private model to get masks
use_last_pri: False

#Extra
get_masks: True
use_one_representation: False
save_model: False
pre_train_shared: True
random_f: False
test_every_epoch: False
