experiment: "miniimagenet"
experiment_name: "miniimagenet"
data_dir: "../data"
checkpoint: "./checkpoints/"

# Experiment
num_runs: 3
ntasks: 20
n_channels: 3
workers: 4
seed: 48
num_iter: 1

#Train
epochs: 70
feats_epochs: 40 #20
meta_epochs: 10
batch_size: 128
pc_valid: 0.02
lr_meta: 0.001 #0.001 
lr_task: 0.01

#Model
head_units: 128
latent_dim: 256
resnet18: False
use_relu: True
resnet_pre_trained: True
use_share: True
use_mask: True
only_shared: False

#Meta
use_meta: True #
mini_tasks: 10 #80
inner_loop: 40 #75

# Use last private model to get masks
use_last_pri: False

#Extra
use_one_representation: False
pre_train_shared: True
random_f: False
train_f_representation: True