# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

num_runs: 3
experiment: "cifar100"
experiment_name: "cifar100"
data_dir: "../data"
checkpoint: "./checkpoints/"

ntasks: 20
n_channels: 3

out_epochs: 100
pri_epochs: 5
mini_tasks: 5
inner_loop: 15
mini_tests: 5

head_units: 32
latent_dim: 128
con_pri_shd: True

batch_size: 128
pc_valid: 0.15
val_iter: 5

lr_factor: 3
lr_min: 1.0e-06
lr_patience: 5
lr_patience_inner: 5
mom: 0.9

train_first: True

shd_meta: True
pri_meta: False
shd_mini: False
pri_mini: True
shd_task: False
pri_task: True

lr_meta: 0.01
lr_mini: 0.1
lr_task: 0.01

workers: 4
seed: 48
