# Base on the code: https://github.com/facebookresearch/Adversarial-Continual-Learning

experiment: "cifar100"
experiment_name: "cifar100"
data_dir: "../data"
checkpoint: "./checkpoints/"

# Experiment
num_runs: 3
ntasks: 20
n_channels: 3
workers: 4
seed: 48

#Train
epochs: 70
feats_epochs: 20
meta_epochs: 10
batch_size: 128
pc_valid: 0.15
lr_meta: 0.01
lr_task: 0.1

#Model
head_units: 64
latent_dim: 128
resnet18: False
resnet_pre_trained: True
task_embedding: False

#Meta
use_meta: True
mini_tasks: 10
inner_loop: 40

# #Modelo Completo:
use_share: True
con_pri_shd: False
use_private: True
use_mask: True
only_shared: False

# Memory
use_memory: False
prob_use_mem: 0.5
mem_size: 5

# Use last private model to get masks
use_last_pri: False

#Extra
get_masks: False
use_one_representation: False
save_model: False
