# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
experiment: "imagenet"
experiment_name: "imagenet"
data_dir: "/mnt/nas2/GrimaRepo/datasets"
checkpoint: "./checkpoints/"
# Experiment
num_runs: 1
ntasks: 20
n_channels: 3
workers: 0
seed: 48
#Train
epochs: 20
feats_epochs: 20
meta_epochs: 10
epochs_inner_task: 1
batch_size: 128
pc_valid: 0.15
lr_meta: 0.01
lr_task: 0.01

#Model
head_units: 64
latent_dim: 128
resnet18: False
resnet_pre_trained: True

#Meta
use_meta: True
mini_tasks: 20
inner_loop: 20

#Optimizer
shad_meta: True
priv_meta: False
priv_l_meta: False
head_meta: False
shad_task: False
priv_task: True
priv_l_task: True
head_task: True
# Regularization
mask_reg: False
mask_theta: 0.001
diff_reg: False
diff_theta: 0.01
# Solo modelo Azul (1):
# use_share: True
# con_pri_shd: False
# use_private: False
# use_mask: False

# # Modelo Azul y verdes, sin mascara (2):
# use_share: True
# con_pri_shd: True
# use_private: True
# use_mask: False

# #Modelo Azul y verdes, con mascara sin concatenar:
# use_share: True
# con_pri_shd: False
# use_private: True
# use_mask: True

# #Modelo verdes, con mascara sin concatenar:
# use_share: False
# con_pri_shd: False
# use_private: True
# use_mask: False

# #Modelo Completo:
use_share: True
con_pri_shd: False
use_private: True
use_mask: True
only_shared: False


# Memory
use_memory: False
prob_use_mem: 0.5
mem_size: 20

#task-free
mask_select: 'random' # random, mean
num_masks: 1 # random >= 1; mean == 1
mask_per_class: False
